packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  tesseract.js: false
  unrs-resolver: false
  workerd: true

onlyBuiltDependencies:
  - '@google/genai'
  - 'esbuild'
  - 'protobufjs'
  - 'workerd'

overrides:
  rolldown: '1.2.3'
